#! /bin/sh

#
# chkconfig: 35 99 99
# description: OpenStack Cloud Server Agent
#

. /etc/rc.d/init.d/functions

DAEMON=/usr/bin/cloudagent
LOCKFILE=/var/lock/subsys/cloudagent
PIDFILE=/var/run/cloudagent.pid

cloudagent_start() {
  echo -n $"Starting cloudagent: "
  if [ ! -f "$LOCKFILE" ] ; then
    $DAEMON && echo_success || echo_failure
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
  else
    echo_failure
    RETVAL=1
  fi
}

cloudagent_stop() {
  echo -n $"Stopping cloudagent: "
  kill -9 $(cat $PIDFILE 2>/dev/null) > /dev/null 2>&1 && echo_success || echo_failure
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
}

case "$1" in
  start)
    cloudagent_start
    ;;
  stop)
    cloudagent_stop
    ;;
  restart)
    cloudagent_stop
    cloudagent_start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    RETVAL=1
esac

exit $RETVAL
